export const TEST_TYPE = 'TEST_TYPE' as const;
export const ADD_PUBLICATION_ACTION_TYPE = 'ADD_PUBLICATION_ACTION_TYPE' as const;
export const ADD_EPOCHS_ACTION_TYPE = 'ADD_EPOCHS_ACTION_TYPE' as const;
export const FILTER_PUBLICATIONS_ACTION_TYPE = 'FILTER_PUBLICATIONS_ACTION_TYPE' as const;
